spring.application.name=Sprint19-Challenge

server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/s19ch
spring.datasource.username=postgres
spring.datasource.password=Firtina1820*

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.jdbc.bind=trace

spring.jpa.hibernate.ddl-auto=update
